@startuml
title ページ遷移図
state "top/bbs"  as bbs
bbs: 商品一覧
bbsdel:GET 削除確認\nPOST 削除
write:GET フォーム\nPOST 書き込み

[*]->bbs
bbs-->bbsdel:リンク\ntid
bbsdel-->bbsdel:POST\ntid
bbs-->write:リンク
write-->write:POST\nname,body
@enduml