
@startuml
left to right direction
package モデル{
class ペット{
	-ペットID
	-種類ID
	-年齢
	-値段
}

class 種類{
	-種類ID
	-種類
}

class ユーザー{
	-ユーザーID
	-ユーザー名
	-パスワード
}

class 予約{
	-予約番号
	-ペットID
	-値段
	-日時
}

class ペットDB{
	+全ペット検索()
	+種類IDで検索()
	+ペットIDで検索()
	+追加()
	+変更()
	+削除()
}

class 種類DB{
	+全種類検索()
	+種類IDで検索()
	+追加()
	+変更()
	+削除()
}

class ユーザーDB{
	+ログイン()
}

class 予約DB{
	+全予約検索()
	+ユーザーIDで検索()
	+追加()
	+削除()
}
}

package 画面{
class トップ画面
class ログイン画面
class 予約画面
class 追加確認画面
class 削除確認画面
class 予約確認画面
class 予約一覧画面
}

ペットDB "1" *-- ペット
種類DB "1" *-- 種類
ユーザーDB "1" *-- ユーザー
予約DB "1" *-- 予約
ペット -> 種類

トップ画面-->ユーザーDB
トップ画面-->ペットDB
ログイン画面-->ユーザーDB


@enduml